// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJQR4GRPHP0MzYR-jzKY75nlMakg1ofpc',
    appId: '1:103341885093:android:3f5d66e981f0c4317daf4c',
    messagingSenderId: '103341885093',
    projectId: 'sarandjjtheday',
    databaseURL: 'https://sarandjjtheday-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sarandjjtheday.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdkjGmyFD1n1xZ2jYNLxKQoLM-8n5AnDE',
    appId: '1:103341885093:ios:68a05a6347b1658c7daf4c',
    messagingSenderId: '103341885093',
    projectId: 'sarandjjtheday',
    databaseURL: 'https://sarandjjtheday-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sarandjjtheday.appspot.com',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGJnt2tIJ9IDXSbu9JCf9aVpotI-hVI4E',
    appId: '1:103341885093:web:c56e442e9ff30c277daf4c',
    messagingSenderId: '103341885093',
    projectId: 'sarandjjtheday',
    authDomain: 'sarandjjtheday.firebaseapp.com',
    databaseURL: 'https://sarandjjtheday-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sarandjjtheday.appspot.com',
    measurementId: 'G-74XN418279',
  );

}